services:
  traefik:
    image: traefik:v3.5
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - gateway-network
    labels:
      - "traefik.enable=true"

      # Router para el dashboard
      - "traefik.http.routers.traefik.rule=Host(`ops.localhost`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"


  neo4j:
    image: neo4j:5.22.0-community
    restart: always
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    volumes:
      - neo4j_data:/data
      - ./import:/import
    networks:
      - gateway-network
    ports:
      - "7474:7474"
      - "7687:7687"
    labels:


      - "traefik.http.routers.traefik.rule=Host(`db.localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.db.entrypoints=web"
      - "traefik.http.services.db.loadbalancer.server.port=7474"
      # Middleware de autenticación básica
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=db:$$2y$$05$$9Io5.3qZkfuBRD0haJhLPON2c9.5G1C2OF0Gkmdew0sWgyFOFv4oO"
      - "traefik.http.routersdb.traefik.middlewares=dashboard-auth"
      

  backend:
    build: ./backend
    restart: always
    depends_on:
      - neo4j
    env_file:
      - .env
    networks:
      - gateway-network
    labels:
      - "traefik.enable=true"

      # API disponible en api.localhost/api/
      - "traefik.http.routers.backend.rule=Host(`api.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"


      # Middleware rateLimit (máx 5 req/s por cliente)
      - "traefik.http.middlewares.api-ratelimit.ratelimit.average=5"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.burst=10"

      # Aplicar los 2 middlewares al router
      - "traefik.http.routers.backend.middlewares=api-ratelimit"


volumes:
  neo4j_data:
    driver: local

networks:
  gateway-network:
    driver: bridge